version: '3'
services:
  postgres:
    image: 'postgres:latest'
    logging:
      driver: none
  redis:
    image: 'redis:latest'
    logging:
      driver: none
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
    logging:
      driver: none
  api:
    build:
      dockerfile: ./server/Dockerfile.dev
      context: ./
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
      - ./vinegar-credentials.json:/root/.config/vinegar-credentials.json
    environment:
      # get these from owner
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/vinegar-credentials.json
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSWORD_SALT=
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  interval:
    build:
      dockerfile: ./interval/Dockerfile.dev
      context: ./
    volumes:
      - /app/interval/node_modules
      - ./interval:/app/interval
    depends_on:
      - api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
