version: '3'
services:
  postgres:
    image: 'postgres:latest'
    logging:
      driver: none
  redis:
    image: 'redis:latest'
    logging:
      driver: none
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
    logging:
      driver: none
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      # get these from owner
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSWORD_SALT=
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_PASSWORD= # should be empty
      - POSTGRES_PORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  interval:
    build:
      dockerfile: Dockerfile.dev
      context: ./interval
    volumes:
      - /app/node_modules
      - ./interval:/app
    depends_on:
      - api
    environment:
      # copy of api's environment
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_PASSWORD= # should be empty
      - POSTGRES_PORT=5432
