apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: joinvinegar-com-tls
spec:
  secretName: joinvinegar-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: joinvinegar.com
  dnsNames:
    - joinvinegar.com
    - www.joinvinegar.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - joinvinegar.com
          - www.joinvinegar.com

