FROM node:latest
RUN apt-get update && \
    apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
      libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
      libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
      libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
      libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update
RUN apt-get install -y cabextract
RUN apt-get install -y xfonts-utils fontconfig fonts-liberation libfontenc1 libxfont1 xfonts-encodings
RUN wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb && dpkg -i ttf-mscorefonts-installer_3.6_all.deb && rm ttf-mscorefonts-installer_3.6_all.deb

WORKDIR "/app"
RUN mkdir shared
COPY ./shared ./shared
COPY ./shared/fonts /usr/share/fonts
RUN fc-cache -fv
RUN mkdir worker

WORKDIR "/app/worker"
COPY ./worker/package.json ./
RUN yarn
COPY ./worker .
CMD ["yarn", "serve"]
